### ISSUE TITLE
Bug in quantum_rel_entr when 2nd argument is numeric but 1st argument is not

### ISSUE THREAD

**Issue by Mark-L-Stone** [hfawzi/cvxquad#1]
There is a bug in quantum_rel_entr which is triggered when 2nd argument is numeric but 1st argument is not.

Line 69
`elseif cvx_isconstant(A) || cvx_isconstant(B)`
of quantum_rel_entr.m should not have 
` || cvx_isconstant(B)`
because
`cvx_optval = -quantum_entr(A,m,k) - trace_logm(B,A,m,k);`
is triggered by satisfying this, is not correct for that case, and and will trip an error in trace_logm.

I leave it to you whether to add an 
` elseif cvx_isconstant(B)`
with a following appropriate line of code. As far as I know (I could be wrong), that is not necessary, but I leave it to you whether there's a more efficient path than skipping to the affine code at that point.

**Comment by hfawzi** [comment]
Thanks for pointing this out. I've fixed this bug some time ago (check newest version of quantum_rel_entr). Let me know if the problem still persists.

**Comment by Mark-L-Stone** [comment]
Yes, it is fixed now.

Sorry, I downloaded cvxquad in  Oct., but didn't use it until yesterday, and somehow missed the notice of bug fix for quantum_rel_entr on the download page.
