### ISSUE TITLE
CVXQUAD's Pade approximation not used for log_det, but used for entr and rel_entr

### ISSUE THREAD

**Issue by Mark-L-Stone** [hfawzi/cvxquad#2]
I put CVXQUAD;s exponential.m in the CVX sets directory,  CVXQUAD's Pade approximation was invoked for `entr` and` rel_entr`., as expected.

However, CVX's successive approximation method was used for `log_det` .  I have not looked to see exactly which "exponential cone" inducing functions or circumstances use CVX's successive approximation method rather than CVXQUAD's Pade approximation.

**Comment by hfawzi** [comment]
Thanks for pointing this out.  It seems in fact that in CVX, log_det (and even the function log) does not invoke the exponential cone (unlike rel_entr) -- the constraints are set up "directly" in a way which I still do not understand.

If you want to use log_det with Pade approximation here is a simple way to do this using the fact that log_det(X) = n*log(det_rootn(X)) [which is the way log_det is implemented in CVX anyway]: If you have a constraint log_det(X) >= t you can write instead (u is an additional variable):

log(u) >= t/n
det_rootn(X) >= u

which in turn is equivalent to

{t/n,1,u} == exponential(1);  %log(u) >= t/n
det_rootn(X) >= u;

**Comment by Mark-L-Stone** [comment]
Thanks.

I tired it on a problem which includes a -log_det(X) in the objective function. I inserted your constraints, also declared t as a variable, and used -t in place of -log_det(X) in the objective function and got about a 4 times speedup vs. CVX's successive approximation method, with good agreement in the solutions.

**Comment by Mark-L-Stone** [comment]
The easiest way to get CVXQUAD's Pade approximation to be invoked for log is to replace `log(cvx_expression)` with `-rel_entr(1,cvx_expresion) `

To get CVXQUAD's Pade approximation to be invoked tor
`y*exp(x/y) <= z`
replace it with either
`{x,y,z} == exponential(1)`
or
`x + rel_entr(y,z) <= 0`

So to get CVXQUAD's Pade approximation to be invoked for exp, replace `exp(cvx_expression)` with either
```
variable z
{x,y,z} == exponential(1)
```
or
```
variable z
cvx_expression + rel_entr(1,z) <= 0
```
