### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dstahlke** [hfawzi/cvxquad#7]
I have been attempting to get this ported to Julia's Convex.jl.  I believe the maintainer of Convex.jl (or maybe myself) has contacted you about this a while back.  He was requesting that we cite the cvxquad license in the Convex.jl license file.  Can you please add a license to your code?  I believe that either BSD or MIT would be compatible with Convex.jl, though of course it's your software and your choice.

**Comment by hfawzi** [comment]
Done, I added an MIT license

**Comment by dstahlke** [comment]
FYI, this port is now merged into Convex.jl.  Much thanks to you for writing the original, and for working out all the theory for us!

**Comment by hfawzi** [comment]
No problem, thanks to you for porting it to Julia! ;)
