### ISSUE TITLE
undefined function randRho and Tx

### ISSUE THREAD

**Issue by husisy** [hfawzi/cvxquad#8]
I try to run `examples/rel_entr_entanglement.m`, but get  the following error.

```matlab
>> rel_entr_entanglement
Undefined function or variable 'randRho'
```
I've searched the whole repo and cannot find its definition (similar issue for `Tx`). Could you please provide these functions? thx

**Comment by hfawzi** [comment]
These functions are available from the quantinf package, available here: https://www.dr-qubit.org/matlab.html

**Comment by husisy** [comment]
get it, thx.
